{"name": "test_update_user_without_auth_name_error_message", "status": "passed", "start": 1732447986328, "stop": 1732447986653, "uuid": "b05ec399-8e89-49c9-bc74-65e22c037fbd", "historyId": "366c102589f410b7481d590b8ef87c75", "testCaseId": "366c102589f410b7481d590b8ef87c75", "fullName": "tests.test_updata_user_data.TestUserUpdate#test_update_user_without_auth_name_error_message", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_updata_user_data"}, {"name": "subSuite", "value": "TestUserUpdate"}, {"name": "host", "value": "DESKTOP-BEKDSUT"}, {"name": "thread", "value": "11160-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_updata_user_data"}]}