{"name": "test_create_existing_user_raises_exception", "status": "passed", "attachments": [{"name": "stdout", "source": "40614e58-84d0-40a7-8e0a-378421faa5c4-attachment.txt", "type": "text/plain"}], "start": 1732447970288, "stop": 1732447970572, "uuid": "4a759271-73d2-4c38-9945-c0304c83d4f4", "historyId": "37621dca6a1efad1a991bce77ad13a76", "testCaseId": "37621dca6a1efad1a991bce77ad13a76", "fullName": "tests.test_create_user.TestCreateUser#test_create_existing_user_raises_exception", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "DESKTOP-BEKDSUT"}, {"name": "thread", "value": "11160-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}